### ISSUE TITLE
XojoFormatter issue

### ISSUE THREAD

**Issue by pjrodman** [gkjpettet/better-code-editor#26]
In an interface definition, functions and subs do not have corresponding "end function" or "end sub" lines. The formatter doesn't seem to know this and formats (indents) accordingly. e.g.

interface RADecObject
    function RA() as double
    function Dec() as double
end interface

**Comment by gkjpettet** [comment]
Yep. That's an oversight on my part. I hadn't realise that it was possible to have a `function` / `sub` declaration without a matching `end` statement. I'll take a look at this. It's actually a bit trickier than you might realise to fix as (currently) the formatter does not know that it is within an interface definition when it hits a `function` / `sub` declaration. Fixing this bug will require addressing that.

**Comment by gkjpettet** [comment]
Fixed in commit d71cca3.

You _may_ notice a performance hit with this fix with your 19,000 line file as the block structure has to be parsed frequently. I was testing with 5K lines of code and didn't notice any appreciable slowdown however.

**Comment by pjrodman** [comment]
Thanks. Works great. It's unlikely that any of my end users will be defining interfaces, and I'm the only one that sees that horror 19K+ line Xojoscript content prefix code anyway...
