### ISSUE TITLE
Event firing when the cursor is moved to a new line.

### ISSUE THREAD

**Issue by pjrodman** [gkjpettet/better-code-editor#29]
An event that fires when the cursor is moved to another line would be useful. e.g. if the cursor is on a line with an error, then the application could display the error message under the editor, etc.

**Comment by gkjpettet** [comment]
Added a `CaretChangedLine` event to both the `BCECanvas` and the `BCEEditorContainer` controls in commit 2eaa693.

**Comment by pjrodman** [comment]
Verified. Thanks.
