### ISSUE TITLE
Setting HighlightCurrentLine to True has no effect

### ISSUE THREAD

**Issue by pjrodman** [gkjpettet/better-code-editor#31]
Setting HighlightCurrentLine to True has no effect (also in the demo app)

**Comment by gkjpettet** [comment]
I can't reproduce this.

If you set `HighlightCurrentLine` to `True` in the demo with the Xojo light theme you won't see anything because it's styled that way. Switch to the Photon theme and enable it and you'll see it works.

**Comment by pjrodman** [comment]
Gotcha. I was using the XojoLight theme.
