### ISSUE TITLE
Sending text to an undrawn BCEEditorContainer

### ISSUE THREAD

**Issue by pjrodman** [gkjpettet/better-code-editor#32]
If you have a BCEEditorContainer on, say, a hidden tab panel that hasn't yet become visible and you try and shove some text into it, you get a nil object exception. The same thing occurs if you try and do the same to a BCEEditorContainer in the Opening event of a window. The workaround is to use a timer to make sure the BCEEditorContainer has been drawn before you give it any text. 

It appears to be an issue with the mBackBuffer property not having been initialised. Perhaps it could be initialised via a lazy computed property.

**Comment by gkjpettet** [comment]
I don't think this is fixable. I believe it relates to the fact that `mBackBuffer` relies on `TrueWindow.BitmapForCaching` to get a correctly scaled `Picture` to draw into. If the container has not yet been drawn then Xojo's framework returns `Nil` for `BitmapForCaching`.

**Comment by pjrodman** [comment]
OK. Is there any way I can determine if the editor has been drawn and is ready to have text thrown at it? I'd rather not modify your code if at all possible.

**Comment by gkjpettet** [comment]
If you could provide a basic sample project that reproduces this I can take a look and see if there’s an elegant solution.

**Comment by pjrodman** [comment]
Add the following code to the end of the WinDemo Opening event and run the demo application:

Code.Editor.LineManager.DeleteAllLines(true, true)
Code.Editor.Insert("Hello World", 0, true)
Code.Editor.CaretPosition = 0
Code.Editor.ScrollToCaretPos

**Comment by pjrodman** [comment]
My "elegant" solution would be to cache the text until the widget is ready to accept the text, either via a (say) Ready event, or until I use a timer to poll a (say) Ready boolean variable.

**Comment by gkjpettet** [comment]
Fixed in commit 743d95f.

No need for timers or other inelegant solutions.

**Comment by pjrodman** [comment]
Verified. Excellent! I can remove a bunch of eye-rolling workarounds.
