### ISSUE TITLE
Cannot use ConstructContextualMenu event

### ISSUE THREAD

**Issue by pjrodman** [gkjpettet/better-code-editor#33]
Cannot use ConstructContextualMenu event on the editor widget (never gets called).

e.g. in the sample project, add the ConstructContextualMenu event to the Code control in the WinDemo window and populate it with the code:

```
base.AddMenu new DesktopMenuItem("test")
return true
```

**Comment by pjrodman** [comment]
I tried faking it with the MouseDown event and IsContextualMenu, but that event also does not fire.

**Comment by gkjpettet** [comment]
Added in commit 158670c a `ShouldConstructContextualMenu` event to both `BCECanvas` and `BCEEditorContainer`. Use this instead of `ConstructContextualMenu`.

**Comment by pjrodman** [comment]
Half way there, but...

In BCECanvas.DidContextualClick you have this code:

If ShouldConstructContextualMenu(base, x, y) Then
  Call base.PopUp(Self.Window.Left + x, Self.Window.Top + y)
End If

This won't do anything except show the contextual menu. I suspect the correct code should be:

If RaiseEvent ShouldConstructContextualMenu(base, x, y) Then
  dim selectedItem as DesktopMenuItem = base.PopUp(Self.Window.Left + x, Self.Window.Top + y)
  if selectedItem <> nil then RaiseEvent DidSelectContextualMenuItem(selectedItem)
End If
 
This would require a new event definition, DidSelectContextualMenuItem(selectedItem as DesktopMenuItem)

**Comment by gkjpettet** [comment]
Thanks @pjrodman. I'm not overly familiar with contextual menus. I've added a `DidSelectContextualMenuItem` event in commit 93dadc0 as you suggested and it now seems to work.

**Comment by pjrodman** [comment]
Verified. Thanks.
