### ISSUE TITLE
BCEEditorContainer is not Enabled-enabled

### ISSUE THREAD

**Issue by pjrodman** [gkjpettet/better-code-editor#35]
The BCECanvas is now aware of the Enabled property, but the BCEEditorContainer is not. Not critical since the enclosed BCECanvas is public and can be Enabled/Disabled separately, but would be nice to have.

**Comment by gkjpettet** [comment]
Fixed in commit c61df0a.

**Comment by pjrodman** [comment]
Verified. Thanks.
